import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  'what-is-finops': [
    'introduction/what-is-finops',
    {
      type: 'link',
      label: 'FinOpsフレームワーク',
      href: 'https://finops-jp.github.io/ja/docs/framework',
    },
    {
      type: 'link',
      label: 'FinOps用語',
      href: 'https://finops-jp.github.io/ja/docs/assets/terminology',
    },
  ],

  framework: [
    {
      type: 'category',
      label: 'FinOpsフレームワーク',
      link: {
        type: 'doc',
        id: 'framework/index',
      },
      items: [
        'framework/principles',
        {
          type: 'category',
          label: 'FinOpsペルソナ',
          link: {
            type: 'doc',
            id: 'framework/personas/index',
          },
          items: [
          ],
        },
        'framework/phases',
        'framework/maturity-model',
        {
          type: 'category',
          label: 'FinOpsドメイン',
          link: {
            type: 'doc',
            id: 'framework/domains/index',
          },
          items: [
          ],
        },
        {
          type: 'category',
          label: 'FinOpsケイパビリティ',
          link: {
            type: 'doc',
            id: 'framework/capabilities/index',
          },
          items: [
          ],
        },
        'framework/scopes',
      ],
    },
    {
      type: 'link',
      label: 'FinOps用語',
      href: 'https://finops-jp.github.io/ja/docs/assets/terminology',
    },
  ],

  terminology: [
    'assets/terminology'
  ],
};

export default sidebars;
